In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

warnings.filterwarnings('ignore')
df = pd.read_csv('Clustering_Data.csv')
df.head(4)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5

In [3]:
df

Gender        Age    Height      Weight  family_history_with_overweight  \
0          0  21.000000  1.620000   64.000000                               1   
1          0  21.000000  1.520000   56.000000                               1   
2          1  23.000000  1.800000   77.000000                               1   
3          1  27.000000  1.800000   87.000000                               0   
4          1  22.000000  1.780000   89.800000                               0   
...      ...        ...       ...         ...                             ...   
1495       1  29.409825  1.801224  108.156190                               1   
1496       1  28.421533  1.829239  107.108190                               1   
1497       0  18.000000  1.692913   89.938890                               1   
1498       0  18.000000  1.668555   85.607466                               1   
1499       1  23.246702  1.652971   93.310284                               1   

      FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF  \
0        0  2.000000  3.000000     2      0  2.000000    0  0.000000   
1        0  3.000000  3.000000     2      1  3.000000    1  3.000000   
2        0  2.000000  3.000000     2      0  2.000000    0  2.000000   
3        0  3.000000  3.000000     2      0  2.000000    0  2.000000   
4        0  2.000000  1.000000     2      0  2.000000    0  0.000000   
...    ...       ...       ...   ...    ...       ...  ...       ...   
1495     1  2.385502  2.883984     2      0  2.140544    0  1.144876   
1496     1  2.465575  2.935381     2      0  2.480555    0  1.001830   
1497     1  2.818502  3.000000     2      0  1.991251    0  1.492967   
1498     1  2.081238  3.000000     2      0  1.183630    0  1.171770   
1499     1  1.368978  3.000000     2      0  1.953152    0  0.104707   

           TUE  CALC  MTRANS  NObeyesdad  
0     1.000000     3       3           1  
1     0.000000     2       3           1  
2     1.000000     1       3           1  
3     0.000000     1       4           5  
4     0.000000     2       3           6  
...        ...   ...     ...         ...  
1495  1.767468     2       0           2  
1496  1.670313     2       0           2  
1497  0.000000     3       3           2  
1498  0.000000     3       3           2  
1499  0.221830     3       0           2  

[1500 rows x 17 columns]

In [2]:
scaler = StandardScaler()   
scaled_df = scaler.fit_transform(df)

kmeans = KMeans(n_clusters=4)

kmeans.fit(scaled_df)

print(kmeans.cluster_centers_)

[[-6.57531942e-01 -4.71842519e-01 -6.17573310e-01 -9.54997414e-01
  -7.85080596e-01 -4.04947730e-01  2.49583851e-01  6.55788930e-02
  -5.76544438e-01 -1.47642694e-01 -4.18403160e-01  3.82738405e-01
  -1.04446194e-03  8.52476258e-02  1.62877377e-01  4.67049315e-01
  -6.07906160e-01]
 [-1.28199887e-01  1.65984921e+00 -1.28677545e-01  4.46270526e-01
   3.39664602e-01  1.75130774e-01  1.12745755e-01 -1.60159863e-01
   1.97555958e-01 -1.47642694e-01 -1.30535385e-01 -2.17238150e-01
  -1.44410808e-01 -5.81226466e-01 -1.41854576e-01 -1.65594530e+00
   4.79179457e-01]
 [ 4.95659547e-01 -3.50862749e-01  4.70829803e-01  4.65546942e-01
   3.93870982e-01  2.25309627e-01 -2.25071762e-01  1.70321878e-02
   3.34588794e-01 -1.47642694e-01  3.32545935e-01 -1.92335805e-01
   5.70222084e-02  1.69702900e-01 -2.67150285e-02  3.33183170e-01
   2.30631575e-01]
 [ 3.18483126e-02  5.12860981e-01 -1.57598427e-02  2.06844882e-01
   1.58350816e-01 -4.08467007e-01  2.51434027e-01  2.12323293e-02
  -4.39126134e-01  

In [4]:
centroids = kmeans.cluster_centers_

In [5]:
centroids[3]

array([ 3.18483126e-02,  5.12860981e-01, -1.57598427e-02,  2.06844882e-01,
        1.58350816e-01, -4.08467007e-01,  2.51434027e-01,  2.12323293e-02,
       -4.39126134e-01,  6.77310859e+00,  6.41736562e-02,  3.76910697e-01,
        2.38996217e-03, -1.27806527e-02, -6.33506966e-01, -8.27434508e-02,
       -1.01241485e-01])

In [6]:
print(kmeans.labels_)

[0 3 2 ... 2 2 1]


In [7]:
df['labels'] = kmeans.labels_
df.head(4)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  labels  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1       0  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1       3  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1       2  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5       2

In [8]:
df = df.sample(frac=1).reset_index(drop=True)
df.head(4)

Gender   Age   Height      Weight  family_history_with_overweight  FAVC  \
0       1  18.0  1.70165   50.157707                               1     1   
1       1  35.0  1.78000  105.000000                               1     1   
2       1  31.0  1.76000   75.000000                               1     0   
3       0  19.0  1.51000   59.000000                               1     1   

       FCVC  NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  CALC  \
0  1.757466  3.0     2      0  1.153559    0  0.833976  1.616045     2   
1  3.000000  1.0     3      0  3.000000    0  3.000000  1.000000     1   
2  3.000000  3.0     0      0  3.000000    1  3.000000  0.000000     3   
3  3.000000  3.0     1      0  1.000000    0  1.000000  2.000000     2   

   MTRANS  NObeyesdad  labels  
0       3           0       2  
1       0           2       1  
2       1           1       0  
3       4           5       0

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

acc = 0

while acc < 0.9:
    rand = np.random.uniform(0.2, 0.3)
    rand = round(rand, 2)
    train, test = train_test_split(df, test_size=rand)

    train_x = train.drop('labels', axis=1)
    train_y = train['labels']

    test_x = test.drop('labels', axis=1)
    test_y = test['labels']

    knn_clf = KNeighborsClassifier(n_neighbors=7, metric='euclidean')

    knn_clf.fit(train_x, train_y)

    pred = knn_clf.predict(test_x)

    acc = accuracy_score(test_y, pred)
print("Accuracy of the classifier:", acc)
print("Test size:", rand)

Accuracy of the classifier: 0.9088888888888889
Test size: 0.3


In [10]:
df2 = pd.read_csv('Classification_Data.csv')
df2.head(4)

Gender        Age    Height     Weight  family_history_with_overweight  \
0       1  24.481032  1.661277  90.744965                               1   
1       1  29.000000  1.641784  89.424947                               1   
2       1  27.968765  1.673767  89.995034                               1   
3       0  18.024744  1.617192  83.121811                               1   

   FAVC      FCVC  NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  CALC  \
0     1  1.712848  3.0     2      0  1.162153    0  0.458981  0.885532     3   
1     1  1.330700  3.0     2      0  1.880967    0  0.322013  0.000000     2   
2     1  1.961069  3.0     2      0  2.652327    0  0.569310  0.319008     2   
3     1  2.976509  3.0     2      0  1.022705    0  1.025690  0.313016     3   

   MTRANS  NObeyesdad  
0       0           2  
1       0           2  
2       0           2  
3       3           2

In [11]:
pred2 = knn_clf.predict(df2)

In [12]:
pred2.shape

(611,)

In [13]:
df2['labels'] = pred2
df2.head(7)

Gender        Age    Height     Weight  family_history_with_overweight  \
0       1  24.481032  1.661277  90.744965                               1   
1       1  29.000000  1.641784  89.424947                               1   
2       1  27.968765  1.673767  89.995034                               1   
3       0  18.024744  1.617192  83.121811                               1   
4       0  18.106820  1.602129  82.412665                               1   
5       1  21.379676  1.701413  96.710735                               1   
6       1  21.353237  1.709731  95.032177                               1   

   FAVC      FCVC       NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  \
0     1  1.712848  3.000000     2      0  1.162153    0  0.458981  0.885532   
1     1  1.330700  3.000000     2      0  1.880967    0  0.322013  0.000000   
2     1  1.961069  3.000000     2      0  2.652327    0  0.569310  0.319008   
3     1  2.976509  3.000000     2      0  1.022705    0  1.025690  0.313016   
4     1  2.319648  3.000000     2      0  1.107164    0  0.692123  0.304020   
5     1  2.000000  2.961192     2      0  2.623344    0  0.981686  1.355370   
6     1  2.000000  2.973476     2      0  2.000000    0  0.000000  1.331527   

   CALC  MTRANS  NObeyesdad  labels  
0     3       0           2       1  
1     2       0           2       1  
2     2       0           2       1  
3     3       3           2       0  
4     3       3           2       0  
5     3       3           2       2  
6     3       3           2       2

In [14]:
pred2

array([1, 1, 1, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 3, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,

In [15]:
df2['labels'].value_counts()

2    520
1     86
0      4
3      1
Name: labels, dtype: int64